services:
  proxy:
    image: nginx
    container_name: 'block-explorer-proxy'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    volumes:
      - "../proxy:/etc/nginx/templates"
    environment:
      BACK_PROXY_PASS: http://block-explorer-backend:4000
      FRONT_PROXY_PASS: http://block-explorer-frontend:3000
      STATS_CORS_ORIGIN_URL: ${STATS_CORS_ORIGIN_URL}
    ports:
      - target: 5050
        published: 5050
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
